// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb.h for the primary calling header

#ifndef VERILATED_VTB___024ROOT_H_
#define VERILATED_VTB___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_threads.h"
#include "verilated_timing.h"


class Vtb__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        IData/*31:0*/ tb__DOT__bus_wdata;
        SData/*11:0*/ tb__DOT__u_led__DOT__val;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__4__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__5__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__6__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__7__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__8__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__9__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__10__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__11__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__4__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__5__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__6__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__7__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__8__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__9__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__10__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__11__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__4__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__5__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__6__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__7__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__8__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__9__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__10__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__11__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__4__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__5__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__6__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__7__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__8__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__9__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__10__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__11__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__0__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__1__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__2__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__3__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__4__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__0__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__1__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__2__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__3__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__4__KET____DOT__sel;
        VlWide<4>/*119:0*/ tb__DOT__u_led__DOT__led_g_q;
        VL_OUTW(led_g_o,119,0,4);
        VL_OUTW(led_b_o,119,0,4);
        VlWide<4>/*119:0*/ tb__DOT__u_led__DOT__led_b_q;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_hd833e037__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_he7c66dbc__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_h8f2ef9a1__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_h8f223bc1__0;
    };
    struct {
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_h8f26a8df__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_h8f02fc66__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_h8f9bbd0f__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_h8fd62221__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_h8e759b18__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_h8f7efefc__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_h8f31bf2c__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_h8f9e5970__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_h8f0d5fe9__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_h8f7a5f0b__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_hd8532756__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_hd850f4e2__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_hd8c0ed67__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_hd808e424__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_hd869425c__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_he7f5e319__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_hd80e8247__0;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_hda9d64cf__0;
        VL_OUT8(sevensegment_1_o,7,0);
        VL_OUT8(sevensegment_2_o,7,0);
        VL_OUT8(sevensegment_3_o,7,0);
        VL_OUT8(sevensegment_4_o,7,0);
        CData/*0:0*/ tb__DOT__u_cpu__DOT__csr_mtie_q;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__csr_mpie_q;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__csr_mcause_i_q;
        CData/*5:0*/ tb__DOT__u_cpu__DOT__csr_mcause_c_q;
        CData/*7:0*/ __Vdlyvval__tb__DOT__u_lcd__DOT__disp_q__v0;
        CData/*0:0*/ __Vdlyvset__tb__DOT__u_lcd__DOT__disp_q__v0;
        CData/*0:0*/ __Vdlyvset__tb__DOT__u_lcd__DOT__disp_q__v1;
        CData/*7:0*/ __Vdlyvval__tb__DOT__u_lcd__DOT__disp_q__v2;
        CData/*0:0*/ __Vdlyvset__tb__DOT__u_lcd__DOT__disp_q__v2;
        CData/*0:0*/ __Vdlyvset__tb__DOT__u_lcd__DOT__disp_q__v3;
        CData/*7:0*/ __Vdlyvval__tb__DOT__u_lcd__DOT__disp_q__v4;
        CData/*0:0*/ __Vdlyvset__tb__DOT__u_lcd__DOT__disp_q__v4;
        CData/*0:0*/ __Vdlyvset__tb__DOT__u_lcd__DOT__disp_q__v5;
        CData/*7:0*/ __Vdlyvval__tb__DOT__u_lcd__DOT__disp_q__v6;
        CData/*0:0*/ __Vdlyvset__tb__DOT__u_lcd__DOT__disp_q__v6;
        CData/*0:0*/ __Vdlyvset__tb__DOT__u_lcd__DOT__disp_q__v7;
        CData/*4:0*/ __Vdlyvdim0__tb__DOT__u_cpu__DOT__gpr_q__v0;
        CData/*0:0*/ __Vdlyvset__tb__DOT__u_cpu__DOT__gpr_q__v0;
        CData/*0:0*/ __Vdly__tb__DOT__u_cpu__DOT__csr_mie_q;
        IData/*31:0*/ __Vdlyvval__tb__DOT__u_cpu__DOT__gpr_q__v0;
        IData/*31:0*/ __Vdly__tb__DOT__u_cpu__DOT__csr_mepc_q;
        VlUnpacked<IData/*31:0*/, 32> tb__DOT__u_cpu__DOT__gpr_q;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__wb_gpr_wdata;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_slti;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_sltiu;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_sub;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_slt;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_sltu;
        CData/*0:0*/ tb__DOT__u_cpu__DOT____VdfgTmp_h702d1d83__0;
        CData/*0:0*/ tb__DOT__u_cpu__DOT____VdfgTmp_h87ebf8fd__0;
        CData/*0:0*/ tb__DOT__u_cpu__DOT____VdfgTmp_h0a4778a7__0;
        CData/*0:0*/ tb__DOT__u_cpu__DOT____VdfgTmp_h555416eb__0;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_lh;
        CData/*0:0*/ tb__DOT__u_but__DOT__wen_src;
        CData/*0:0*/ tb__DOT__u_but__DOT__wen;
        CData/*0:0*/ tb__DOT__u_but__DOT__sel_ptm;
        CData/*0:0*/ tb__DOT__bus_en;
        CData/*0:0*/ tb__DOT__rng_en;
        CData/*0:0*/ tb__DOT__led_en;
        CData/*0:0*/ tb__DOT__lcd_en;
        CData/*0:0*/ tb__DOT__but_en;
        CData/*0:0*/ tb__DOT__u_rng__DOT__sel_val;
    };
    struct {
        CData/*0:0*/ tb__DOT__u_led__DOT__wstrb_incomp;
        CData/*0:0*/ tb__DOT__u_lcd__DOT__wen;
        CData/*0:0*/ tb__DOT__u_but__DOT__sel_src;
        CData/*3:0*/ tb__DOT__bus_wstrb;
        CData/*0:0*/ tb__DOT__mem_en;
        CData/*0:0*/ tb__DOT__u_but__DOT__sel_stm;
        IData/*31:0*/ tb__DOT__bus_addr;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__ex_expt;
        CData/*0:0*/ tb__DOT__u_led__DOT__wen;
        CData/*2:0*/ tb__DOT__u_cpu__DOT__st_nxt;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__bus_data_q;
        VlUnpacked<CData/*7:0*/, 4> tb__DOT__u_lcd__DOT__disp_q;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_jalr;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__de_ins_imm_i;
        SData/*9:0*/ tb__DOT__u_but__DOT____Vcellout__u_ptm__src;
        SData/*9:0*/ tb__DOT__u_but__DOT__ext_push;
        IData/*19:0*/ tb__DOT__u_but__DOT__ptm_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__0__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__0__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__0__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__1__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__1__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__1__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__2__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__3__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__4__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__5__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__6__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__7__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__8__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__9__KET____DOT__val_q;
        VL_IN8(button_top_i,0,0);
        VL_IN8(button_bottom_i,0,0);
        VL_IN8(button_left_i,0,0);
        VL_IN8(button_right_i,0,0);
        VL_IN8(button_center_i,0,0);
        VL_IN8(joystick_up_i,0,0);
        VL_IN8(joystick_down_i,0,0);
        VL_IN8(joystick_left_i,0,0);
        VL_IN8(joystick_right_i,0,0);
        VL_IN8(joystick_pressed_i,0,0);
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__2__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__2__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__3__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__3__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__4__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__4__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__5__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__5__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__6__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__6__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__7__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__7__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__8__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__8__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__9__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_ptm__DOT__genblk1__BRA__9__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__ext_vld_q;
        IData/*17:0*/ tb__DOT__u_but__DOT__ext_val_q;
        VL_IN8(dip_switches_i,7,0);
        IData/*30:0*/ tb__DOT__u_rng__DOT__lfsr_xor;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__0__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__0__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__0__KET____DOT__val_q;
    };
    struct {
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__1__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__1__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__1__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__2__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__2__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__2__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__3__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__3__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__3__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__4__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__4__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__4__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__5__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__5__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__5__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__6__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__6__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__6__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__7__KET____DOT__src_edge;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__7__KET____DOT__vld_q;
        CData/*0:0*/ tb__DOT__u_but__DOT__u_stm__DOT__genblk1__BRA__7__KET____DOT__val_q;
        CData/*0:0*/ tb__DOT__bus_we;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_sb;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_sh;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_sw;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__ex_ins_is_ls;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__ex_lsu_sz_mask_hi;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__wb_expt;
        CData/*0:0*/ tb__DOT__u_bus__DOT__led_en_q;
        CData/*0:0*/ tb__DOT__u_bus__DOT__tmp_en_q;
        CData/*0:0*/ tb__DOT__u_mem__DOT__err_q;
        CData/*0:0*/ tb__DOT__u_rng__DOT__err_q;
        CData/*0:0*/ tb__DOT__u_led__DOT__err_q;
        CData/*0:0*/ tb__DOT__u_lcd__DOT__err_q;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_rs2_q;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_lw;
        CData/*0:0*/ tb__DOT__u_led__DOT____VdfgTmp_he27f05d9__0;
        CData/*7:0*/ tb__DOT__u_but__DOT__ext_switch;
        SData/*15:0*/ tb__DOT__u_but__DOT__stm_q;
        IData/*31:0*/ tb__DOT__u_rng__DOT__lfsr_q;
        CData/*7:0*/ tb__DOT__u_but__DOT____Vcellout__u_stm__src;
        IData/*31:0*/ tb__DOT__u_mem__DOT__rdata_q;
        VL_IN8(rst_ni,0,0);
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__4__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__5__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__6__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__7__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__8__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__9__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__10__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__1__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__2__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__3__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__4__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__10__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__11__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__0__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__1__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__11__KET____DOT__nxt;
    };
    struct {
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__11__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__8__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__5__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__6__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__7__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__8__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__9__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__10__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__11__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__5__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__6__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__7__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__8__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__9__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__10__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__11__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__11__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__10__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__11__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__4__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__5__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__4__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__6__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__7__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__8__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__1__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__2__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__3__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__4__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__6__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__7__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__8__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__9__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__10__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__2__KET____DOT__genblk1__BRA__11__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__9__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__10__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__11__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__0__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__5__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__6__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__7__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__9__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__7__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__8__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__9__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__10__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__9__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__10__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__5__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__6__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__8__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__10__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__4__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__5__KET____DOT__nxt;
    };
    struct {
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__6__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__7__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__8__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__1__KET____DOT__genblk1__BRA__9__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__0__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__1__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__2__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__3__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__9__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__10__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__11__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__0__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__9__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__10__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__11__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__0__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__1__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__4__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__5__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__0__KET____DOT__genblk1__BRA__6__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__3__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__5__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__6__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__7__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__8__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__8__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__2__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__3__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__4__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__4__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__5__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__6__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__7__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__5__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__6__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__7__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__8__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__9__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__10__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__11__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__5__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__6__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__7__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__8__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__9__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__10__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__5__KET____DOT__genblk1__BRA__11__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__0__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__1__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__2__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__3__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__4__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__5__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__6__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__7__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__8__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__0__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__1__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__2__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__3__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__4__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__5__KET____DOT__sel;
    };
    struct {
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__6__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__7__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__8__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__3__KET____DOT__genblk1__BRA__11__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__0__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__1__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__4__KET____DOT__genblk1__BRA__2__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__5__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__7__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__9__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__10__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__6__KET____DOT__genblk1__BRA__11__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__9__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__10__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__7__KET____DOT__genblk1__BRA__11__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__0__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__1__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__2__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__3__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__8__KET____DOT__genblk1__BRA__4__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__0__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__1__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__2__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__2__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__3__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__3__KET____DOT__nxt;
        CData/*0:0*/ tb__DOT__u_led__DOT__genblk3__BRA__9__KET____DOT__genblk1__BRA__4__KET____DOT__sel;
        CData/*0:0*/ tb__DOT__u_led__DOT__g_en;
        CData/*0:0*/ tb__DOT__u_led__DOT__b_en;
        CData/*0:0*/ tb__DOT__u_led__DOT__r_en;
        VlWide<4>/*119:0*/ tb__DOT__u_led__DOT__led_r_q;
        VL_OUTW(led_r_o,119,0,4);
        CData/*0:0*/ tb__DOT__u_cpu__DOT__ex_bru_cmp;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__wb_csr_we;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__wb_csr_we_mstatus;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__wb_csr_we_mie;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__wb_csr_we_mepc;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__wb_csr_we_mcause;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__wi_csr_we_mstatus;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__wi_csr_we_mcause;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__wb_csr_wdata;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_csrrw;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_csrrs;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_csrrc;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_csrrwi;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_csrrsi;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_csrrci;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__ex_alu_blt;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_csr_rs1;
        QData/*32:0*/ tb__DOT__u_cpu__DOT__ex_alu_add;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__ex_alu_lts;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_alu_xor;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_csr_rdata;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__ex_ins_is_j;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_rs1_q;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__ie_expt_set;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__ie_expt_ret;
        CData/*2:0*/ tb__DOT__u_cpu__DOT__ie_q;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__if_irq_e;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__csr_mie_q;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__csr_meie_q;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_bru_add_op0;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__csr_mstatus;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__csr_mie;
    };
    struct {
        IData/*31:0*/ tb__DOT__u_cpu__DOT__csr_mtvec_q;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__csr_mepc_q;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__csr_mcause;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__pc_q;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__if_expt;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_rs1_pc;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_alu_add_op1;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_alu_sl0;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_alu_sl1;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_alu_sl2;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_alu_sr0;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_alu_sr1;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_alu_sr2;
        IData/*17:0*/ tb__DOT__u_but__DOT__src;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__ex_alu_sub;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_mret;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_ev;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_ecall;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_funct7_eq_v;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_inv_jx;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_inv_bx;
        CData/*0:0*/ tb__DOT__u_cpu__DOT____VdfgTmp_h044e296a__0;
        CData/*0:0*/ tb__DOT__u_cpu__DOT____VdfgTmp_hfbc50a14__0;
        CData/*0:0*/ tb__DOT__u_cpu__DOT____VdfgTmp_hff8699ac__0;
        CData/*0:0*/ tb__DOT__u_cpu__DOT____VdfgTmp_hc685467b__0;
        CData/*0:0*/ tb__DOT__u_cpu__DOT____VdfgTmp_h91c39851__0;
        CData/*0:0*/ tb__DOT__u_cpu__DOT____VdfgTmp_h541efbc5__0;
        CData/*0:0*/ tb__DOT__u_cpu__DOT____VdfgTmp_h9b6faebf__0;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__de_ins_is_inv;
        IData/*31:0*/ tb__DOT__bus_rdata;
        CData/*0:0*/ tb__DOT__u_cpu__DOT__ex_alu_srs;
        CData/*7:0*/ tb__DOT__u_cpu__DOT__wb_lsu_lb;
        SData/*15:0*/ tb__DOT__u_cpu__DOT__wb_lsu_lh;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_rs2_imm;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_alu_sl3;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__ex_alu_sr3;
        CData/*0:0*/ tb__DOT__u_bus__DOT__mem_en_q;
        CData/*0:0*/ tb__DOT__u_bus__DOT__rng_en_q;
        CData/*0:0*/ tb__DOT__u_bus__DOT__lcd_en_q;
        CData/*0:0*/ tb__DOT__u_bus__DOT__but_en_q;
        CData/*3:0*/ tb__DOT__u_but__DOT__sel_q;
        CData/*2:0*/ tb__DOT__u_cpu__DOT__st_q;
        IData/*31:0*/ tb__DOT__u_cpu__DOT__de_ins;
        VL_IN8(clk_i,0,0);
        CData/*0:0*/ __Vdpi_export_trigger;
        CData/*0:0*/ __VnbaEventTrigger;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_ni__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<CData/*0:0*/, 32> __Vm_traceActivity;
    };
    VlEvent __VnbaEvent;
    VlTriggerScheduler __VtrigSched_hd48f37a9__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<2> __VicoTriggered;
    VlTriggerVec<4> __VactTriggered;
    VlTriggerVec<4> __VnbaTriggered;
    VlMTaskVertex __Vm_mtaskstate_13;
    VlMTaskVertex __Vm_mtaskstate_26;
    VlMTaskVertex __Vm_mtaskstate_17;
    VlMTaskVertex __Vm_mtaskstate_20;
    VlMTaskVertex __Vm_mtaskstate_25;
    VlMTaskVertex __Vm_mtaskstate_18;
    VlMTaskVertex __Vm_mtaskstate_16;
    VlMTaskVertex __Vm_mtaskstate_27;
    VlMTaskVertex __Vm_mtaskstate_19;
    VlMTaskVertex __Vm_mtaskstate_22;
    VlMTaskVertex __Vm_mtaskstate_15;
    VlMTaskVertex __Vm_mtaskstate_14;
    VlMTaskVertex __Vm_mtaskstate_23;
    VlMTaskVertex __Vm_mtaskstate_final__nba;

    // INTERNAL VARIABLES
    Vtb__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb___024root(Vtb__Syms* symsp, const char* v__name);
    ~Vtb___024root();
    VL_UNCOPYABLE(Vtb___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
